name:                chotp
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/jkopanski/chotp#readme
license:             BSD3
author:              Jakub Kopański
maintainer:          jkopanski@protonmail.com
copyright:           Copyright (c) 2018 Jakub Kopański
category:            Web
extra-source-files:
  - README.md

default-extensions:
  - DeriveDataTypeable
  - DeriveGeneric
  - LambdaCase
  - FlexibleContexts
  - FlexibleInstances
  # - OverloadedStrings

dependencies:
  - base >= 4.7 && < 5
  - binary
  - distributed-process
  - distributed-process-p2p
  - lifted-async
  - network-transport-tcp
  - mtl
  - random
  - stm
  - time
  - transformers

library:
  source-dirs:      src

executables:
  node:
    main:           Main.hs
    source-dirs:    node
    dependencies:
      - optparse-applicative

tests:
  test:
    main:           Test.hs
    source-dirs:    test
    dependencies:
      - chotp
      - tasty
      - tasty-discover
      - tasty-quickcheck
      - QuickCheck
